version: '3.8'

services:
  kma-rabbitmq:
    container_name: kma-rabbit
    image: rabbitmq:3.9.26-management
    restart: unless-stopped
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./var/mqdata:/var/lib/rabbitmq

  kma-db:
    container_name: kma-db
    image: mariadb:10.9.4
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./docker/db/sql/:/docker-entrypoint-initdb.d/
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  kma-producer:
    container_name: kma-producer
    restart: unless-stopped
    depends_on:
      kma-rabbitmq:
        condition: service_healthy
    build:
      context: ./docker/producer
    working_dir: /var/www/kma
    environment:
      - QUEUE_NAME
      - EXCHANGE_NAME
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    volumes:
      - ./app:/var/www/kma

  kma-consumer:
    container_name: kma-consumer
    restart: unless-stopped
    depends_on:
      kma-rabbitmq:
        condition: service_healthy
    build:
      context: ./docker/consumer
    working_dir: /var/www/kma
    environment:
      - QUEUE_NAME
      - EXCHANGE_NAME
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - MYSQL_HOST=kma-db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./app:/var/www/kma
      - ./var/log/supervisor:/var/log
